### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by toanlk** [ip2location/codeigniter-ip2location#1]
I tried with DB1LITEBIN on Codeigniter 3.1

Message: unpack(): Type V: not enough input, need 4, have 0

Filename: ip2location/IP2Location.php

Line Number: 1106

**Comment by ip2location-com** [comment]
Hi @toanlk 

Can we have the IP address that you are testing on?

Please do remember to use IP2Location IPv6 Database for the query of IPv6 address. You have to use DB1LITEBINIPV6 in your case.

**Comment by toanlk** [comment]
IP Adress: 1.54.214.13
I had used [DB1.LITE] IP-COUNTRY Database (Code: DB1LITEBIN)

**Comment by ip2location-com** [comment]
It is working fine based on our testing on CodeIgniter-3.1.10.

Can you please follow the steps below to make sure the IP2Location BIN Database is download correctly: 

1. Download the DB1LITEBIN file manually from https://lite.ip2location.com/file-download 
2. Unzip the IP2LOCATION-LITE-DB1.BIN.ZIP file 
3. Rename the downloaded BIN database to IP2LOCATION-DB.BIN 
4. Replace the copy in application/libraries/ip2location/

**Comment by toanlk** [comment]
Thank you for your help! My IP2LOCATION-DB.BIN was corrupted. It worked when I replaced with the new one
